Dockerfile, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.yaml
- Helm Chart
- GHA
Release of helm chart and GHA necessary to automatically deploy the µ-services
=> feat: [PQ-317] helm chart and openapi

.github/workflows/deploy_with_github_runner.yml, .github/workflows/release_deploy.yml
=> fix: [PQ-317] add gha for deploy

.github/workflows/action.yml, .github/workflows/release_deploy.yml, Dockerfile, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.yaml, pom.xml
=> fix: PQ-317 bdi deployment

.gitignore, .identity/00_data.tf, .identity/01_github_environment.tf, .identity/99_main.tf, .identity/99_variables.tf, .identity/env/dev/backend.ini, .identity/env/dev/backend.tfvars, .identity/env/dev/terraform.tfvars, .identity/env/prod/backend.ini, .identity/env/prod/backend.tfvars, .identity/env/prod/terraform.tfvars, .identity/env/uat/backend.ini, .identity/env/uat/backend.tfvars, .identity/env/uat/terraform.tfvars, .identity/terraform.sh
Configured `.identity` for repo AZ authorization management.
Configured `.identity` for repo AZ authorization management.
=> feat: [PQ-317] .identity management

pom.xml, src/main/java/it/gov/pagopa/observability/service/PerfKpiService.java, src/test/java/it/gov/pagopa/observability/PerfKpiServiceTest.java
Fix some dependencies:
- Azure kusto-data
- Azure kusto-ingest
- azure.functions.maven.plugin.version
- azure.functions.java.library.version
=> fix: [PQ-345] fix maven dependencies

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> fix: [PQ-345] fix ports spec

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
fix service path
fix service path
=> fix: [PQ-345] fix service path

helm/values-dev.yaml
fix secrets name
fix secrets name
=> fix: [PQ-345] fix secrets name

helm/values-dev.yaml
fix-azure-ad-client-secret
fix-azure-ad-client-secret
=> fix: [PQ-345] fix-azure-ad-client-secret

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
fix service path to apim definition
fix service path to apim definition
=> fix: [PQ-345] fix service path to apim definition

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
=> feat: fix secrets name

helm/values-prod.yaml
=> feat: fix helm secrets

helm/values-prod.yaml
Fixed application insights url in `prod`
Fixed application insights url in `prod`
=> feat: fix ai url

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
fix operation name env keys
fix operation name env keys
=> fix: operation name env keys

.gitignore, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, src/main/java/it/gov/pagopa/observability/service/PerfKpiService.java
Use a dedicated service principal to access Azure Application Insights
Access to Azure Application Insights accordingly with the Azure best practices
=> feat: [PQ-356] use service principal to access application insights

.github/workflows/release_deploy.yml
Fixed semver logic  in case of `skip`
=> fix: fix semver in case of skip

.github/workflows/release_deploy.yml
Introduced skip_release instead of semver input
=> fix: introduced skip_release instead of semver input

.github/workflows/collect_kpi_data.yml, python/collect-bdi-kpi/collect-perf-data.py, python/collect-bdi-kpi/requirements.txt
Added the following stuff:
1. GHA to periodically collect performance data
2. python script used by GHA
Enabling automatic data collection
=> feat: [PQ-335] python script to collect perf data

.github/workflows/collect_kpi_data.yml, python/collect-bdi-kpi/collect-perf-data.py
Empty dates managements
Empty dates managements
=> fix: [PQ-335] Empty dates managements

.github/workflows/collect_kpi_data.yml
fixed notification payload path
=> fix: [PQ-335] fix notification payload path

.github/workflows/collect_kpi_data.yml, python/collect-bdi-kpi/collect-perf-data.py
=> fix: [03-PQ-335] fix date arguments

.github/workflows/collect_kpi_data.yml
Fix input params management in case of schedule dispatch
Fix input params management in case of schedule dispatch
=> fix: [fix04-PQ-335] fix input params in case of schedule dispatch

.github/workflows/send_quarter_kpi_data.yml, openapi/openapi.yaml, python/collect-bdi-kpi/send-quarter-data.py, src/main/java/it/gov/pagopa/observability/CollectPerfData.java, src/main/java/it/gov/pagopa/observability/PerKpiAggregator.java, src/main/java/it/gov/pagopa/observability/service/PerfKpiService.java, src/test/java/it/gov/pagopa/observability/CollectPerfDataTest.java, src/test/java/it/gov/pagopa/observability/PerfKpiServiceTest.java
- Added `saveData` flag on `perf-data` API  to let the caller to decide if persist data or not
- `openapi` improvements
openapi spec and `perf-data` API improvements
=> feat: [PQ-363] add saveData flag and openapi improvements

src/main/java/it/gov/pagopa/observability/PerKpiAggregator.java
Added month number to the json message sent to Data Lake
Added month number to the json message sent to Data Lake
=> feat: [PQ-363] add month to dl message

python/collect-bdi-kpi/collect-perf-data.py
Added dashboard link to slack notification.
=> feat: added dashboard link to slack notification

python/collect-bdi-kpi/collect-perf-data.py
Fixed dashboard link in slack notification
=> fix: dashboard link in slack notification

src/main/java/it/gov/pagopa/observability/service/PerfKpiService.java
In the aggregator function, the kpis `PERF-02` and `PERF-02E` were treated as average instead of sum.
In the aggregator function, the kpis `PERF-02` and `PERF-02E` were treated as average instead of sum.
=> fix: perf-02 and perf-02e sum instead of avg

Dockerfile, helm/Chart.lock, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.yaml, pom.xml
Update helm chart to 7.5 version
Update helm chart to 7.5 version
helm template command
deploy in dev env
=> feat: update helm chart version

src/main/java/it/gov/pagopa/observability/PerKpiAggregator.java
Updated kpi label to send to event hub
Updated kpi label to send to event hub
=> feat: updated kpi label to send to event hub

src/main/java/it/gov/pagopa/observability/PerKpiAggregator.java
fix-update-kpi-name-to-evh
fix-update-kpi-name-to-evh
=> feat: fix-update-kpi-name-to-evh

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml
Upgrade image version to `0.9.5`
Upgrade image version to `0.9.5`
=> fix: helm image version

.github/workflows/deploy_with_github_runner.yml, .github/workflows/release_deploy.yml
GHA set dynmic tag to deploy
GHA set dynmic tag to deploy
=> feat: GHA set dynmic tag to deploy

.github/workflows/deploy_with_github_runner.yml
fix: dynamic-image-tag
fix: dynamic-image-tag
=> fix: dynamic-image-tag
